Add two missing sku data to product context
vtex-apps/store-resources pull request #135
Opened 2020-09-22 14:50 UTC by josantana

#### What is the purpose of this pull request?

Expose two missing sku data to product context, so we don't need to make unnecessary extra requests for such a simple thing. The intent is to present the complementName on product shelves; and also present when products are not sold by ourselves. With this fix we can access this data from the context using `useProductSummary`.

#### Screenshots or example usage

![Screen Shot 2020-09-22 at 11 35 23](https://user-images.githubusercontent.com/5032844/93897816-ea225a00-fcc8-11ea-86a4-3e698de22b11.png)

#### Types of changes

* [x] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

2020-09-22 15:14 UTC, kaisermann approved these changes

2020-09-22 15:14 UTC, kaisermann requested changes

2020-09-22 15:14 UTC, kaisermann commented on CHANGELOG.md
> +- Add new fields to the SKU from the `products` query.
Add which fields here please 😁

2020-09-22 15:20 UTC, josantana commented on CHANGELOG.md
> +- Add new fields to the SKU from the `products` query.
Done!

2020-10-05 19:52 UTC, josantana commented
Can anyone help me to approve this, please?

2020-10-06 14:59 UTC, klzns requested changes
Thanks for the pull request! Just a minor fix in the changelog entry

2020-10-06 14:59 UTC, klzns commented on CHANGELOG.md
> +- Add `complementName` and `sellerName` to the SKU on `products` query.
```suggestion
- `itemsWithSimulation` query.
```

The changes to the changelog should be under the [Unreleased] section. Example:

```diff
 ## [Unreleased]
+### Added
+- Add `complementName` and `sellerName` to the SKU on `products` query.

 ## [0.71.0] - 2020-09-22
```

2020-10-07 16:12 UTC, klzns commented
Fixed by https://github.com/vtex-apps/store-resources/pull/132

2020-10-07 16:12 UTC, closed without merging